language: python

python:
  - "3.6"
  
install:
  - pip install -r requirements.txt
  
script: true
    - nosetests --with-coverage --coverage report
    
script: 
  - python TestCalculator.py
  
  deploy:
  provider: heroku
  api_key: 
    secure: 05456bff-67aa-491b-8415-68132ee87f3a
  app: test-my-travisci-project
  on:
    repo: jimting/GitProjectTutorialExample
  #Setting your heroku Procfile here!!!
  run:
    "web: gunicorn app_run:app"
